plugin.directory: "storage-backends/elasticsearch/target"
plugin:
   name: "elasticsearch"
   jar.name: "elasticsearch-store-1.0.0-SNAPSHOT.jar"
   conf:
    host: "http://localhost:9200"
kafka:
  topic: alerts
  stream.threads: 2
  consumer:
    bootstrap.servers: localhost:9092
    auto.offset.reset: latest
    group.id: alert-manager-store
    enable.auto.commit: false