alert.store:
  pluginDirectory: "./storage-backends/"
  plugins:
  - name: elasticsearch
    jarName: "elasticsearch-store.jar"
    host: "http://elasticsearch:9200"
    config: {"aws-iam-auth-required":false}

es:
  index.name: subscription
  create.index.if.not.found: true
  doctype: details
  host: "http://elasticsearch:9200"
  config: {"aws-iam-auth-required":false}
  connection.timeout: 5000
  max.connection.idletime: 1000
  max.total.connection: 1000
  read.timeout: 1000

kafka:
  producer:
    bootstrap.servers: kafkasvc:9092
    client.id: am_producer
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
    request.timeout.ms: 40000
    topic: alerts
    
management:
  context-path: "/admin"
  metrics:
    export:
      jmx:
        domain: spring
    enable:
      jvm: false
      tomcat: false
      system: false
      process: false
