es:
  index.name: subscription
  create.index.if.not.found: true
  doctype: _doc
  urls: "http://elasticsearch:9200"
  connection.timeout: 5000
  max.connection.idletime: 1000
  max.total.connection: 1000
  read.timeout: 1000

kafka:
  producer:
    bootstrap.servers: kafkasvc:9092
    client.id: am_producer
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
    request.timeout.ms: 40000
    topic: alerts

alert.store:
  pluginDirectory: "storage-backends/elasticsearch/target"
  plugins:
  - name: elasticsearch
    jarName: "elasticsearch-store-1.0.0-SNAPSHOT.jar"
    conf:
     host: "http://elasticsearch:9200"
     template: ""

mail:
  additional-validator-expression: ^[A-Z0-9._%+-]+@domain.com$
