alert.store:
  pluginDirectory: "storage-backends/elasticsearch/target"
  plugins:
  - name: elasticsearch
    jarName: "elasticsearch-store-1.0.0-SNAPSHOT.jar"
    host: "http://elasticsearch:9200"
    config: {"aws-iam-auth-required":false}